# frozen_string_literal: true

source("https://rubygems.org")

gem("byebug")
gem("minitest")
gem("rake")
gem("rubocop", require: false)
gem("rubocop-minitest", require: false)
gem("rubocop-rake", require: false)
