#!/bin/env ruby

gui do
  install "firefox"
  install "visual-studio-code"
  install "skype"
  install "zoom"
  install "vlc"
  install "steam"
  install "spotify"
  install "slack"
  install "gimp"
  install "qemu"
  install "localsend"
  install "pinta"
  install "xournalpp"
  install "alacritty"

  macos do
    install "iterm2"
    install "flux"
  end

  windows do
    install "discord"
    install "flux"
  end
end

unix do
  install "zsh"
  install "zellij"
  install "rbenv"
  install "nvm"
  install "rcm"
  install "antigen"
  install "vundle"
  install "heroku"
  install "ripgrep"
  install "btop"
  install "fzf"
  install "fd"
end

install "ollama"
install "fastfetch"
install "vim"
