#!/bin/env ruby

unix do
  install "vim"
  install "zsh"
  install "rbenv"
  install "rcm"
  install "antigen"
  install "vundle"
  install "fzf"
end

macos do
  install "iterm2"
end

windows do
  install "discord"
end

install "firefox"
install "atom"
install "vim"
install "skype"
install "flux"
install "vlc"
install "steam"
install "spotify"
