name: Setup CI

on: push

jobs:
  test:
    strategy:
      matrix:
        platform:
          - name: ubuntu
            runner: ubuntu-latest
            script: bin/bootstrap/linux
            env:
              DISPLAY: 1
          - name: macos
            runner: macos-latest
            script: bin/bootstrap/macos
            env:
              DISPLAY: 1
          - name: ubuntu-headless
            runner: ubuntu-latest
            script: bin/bootstrap/linux
            env: {}
          - name: macos-headless
            runner: macos-latest
            script: bin/bootstrap/macos
            env: {}
          - name: windows
            runner: windows-latest
            script: bin/bootstrap/windows.bat
            env: {}
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runner }}
    env: ${{ matrix.platform.env }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Install Winget
        if: ${{ matrix.platform.name == 'windows' }}
        uses: Cyberboss/install-winget@v1
      - name: ⚙️ Setup
        run: ${{ matrix.platform.script }}
